//
//  CustomBottomNavBar.swift
//  learning
//
//  Created by macbook on 8/30/26.
//

import SwiftUI

struct CustomBottomNavBar: View {
    @Binding var selectedTab: Int

    private let tabs: [(icon: String, title: String, color: Color)] = [
        ("list.clipboard.fill", "Tugas", .cartoonYellow),
        ("sun.max.fill", "Hari Ini", .cartoonPink),
        ("flame.fill", "Kebiasaan", .cartoonOrange),
        ("hourglass.circle.fill", "Fokus", .cartoonLavender),
        ("person.crop.circle.fill", "Profil", .cartoonMint)
    ]

    dynamic var body: some View {
        HStack(spacing: 4) {
            ForEach(0..<tabs.count, id: \.self) { index in
                let tab = tabs[index]
                CartoonTabButton(
                    icon: tab.icon,
                    title: tab.title,
                    index: index,
                    selectedTab: $selectedTab,
                    activeColor: tab.color
                )
            }
        }
        .padding(.horizontal, 4)
        .padding(.vertical, 7)
        .background(Color.white)
        .clipShape(Capsule())
        .overlay(
            Capsule().stroke(Color.cartoonBorder, lineWidth: 2.2)
        )
        .shadow(color: .cartoonBorder, radius: 0, x: 3, y: 3)
        .padding(.horizontal, HIGSpacing.xs)
        .padding(.bottom, 6)
    }
}

// Tombol Tab Kartun Interaktif (Expand Full Width saat isSelected)
struct CartoonTabButton: View {
    let icon: String
    let title: String
    let index: Int
    @Binding var selectedTab: Int
    let activeColor: Color

    var isSelected: Bool { selectedTab == index }

    dynamic var body: some View {
        Button {
            withAnimation(.spring(response: 0.26, dampingFraction: 0.8)) {
                selectedTab = index
            }
        } label: {
            HStack(spacing: 4) {
                Image(systemName: icon)
                    .font(.system(size: isSelected ? 14 : 13.5, weight: .black))

                if isSelected {
                    Text(title)
                        .font(.system(size: 11, weight: .heavy, design: .rounded))
                        .lineLimit(1)
                        .transition(.scale(scale: 0.85).combined(with: .opacity))
                }
            }
            .foregroundColor(.cartoonTextPrimary)
            .padding(.vertical, 8)
            .padding(.horizontal, isSelected ? 10 : 8)
            .frame(maxWidth: isSelected ? .infinity : nil)
            .frame(minHeight: 40)
            .background(isSelected ? activeColor : Color.clear)
            .clipShape(Capsule())
            .overlay(
                Capsule().stroke(isSelected ? Color.cartoonBorder : Color.clear, lineWidth: 1.8)
            )
            .contentShape(Rectangle())
        }
        .accessibilityIdentifier("tab_\(index)")
        .accessibilityLabel(title)
        .buttonStyle(CartoonPressButtonStyle(pressOffset: 1.0))
    }
}

#Preview {
    CustomBottomNavBar(selectedTab: .constant(0))
        .padding()
        .background(Color.cartoonBg)
}

// PATCH-THUNKS-BEGIN (generated by `patchcli prepare` — DO NOT EDIT)
// @generated
// =========================================================================
// AUTOGENERATED BY `patchcli prepare` — DO NOT EDIT THIS SECTION.
//
// Do NOT edit any code in this generated section — neither by hand NOR with
// an AI coding assistant (Copilot, Cursor, Claude, etc.).
//
// Reason: this block is REGENERATED on every `patchcli prepare` run (which
// also runs automatically inside `patchcli build`/`push`/`release`). Any
// manual change here is SILENTLY OVERWRITTEN on the next prepare, and an
// inconsistent thunk can break the OTA fingerprint (causing a MISMATCH that
// blocks your release).
//
// To change a view's behaviour: edit the VIEW SOURCE FILE itself — never
// this generated thunk. To remove this section entirely, delete the block
// from BEGIN to END and re-run `patchcli prepare` (it recreates it).
// =========================================================================
// Patch kept the patch-thunk code for the view(s) below in YOUR file because each is
// declared `private`/`fileprivate` (or its body host-resolves a `private` member) —
// and Swift access control is file-scoped, so a thunk in the separate
// `Patch/Generated/` folder cannot reach it. Only the minimum that genuinely needs
// file-scoped access is here.
// CustomBottomNavBar: helper methods kept here — its body reads private member(s): tabs.
//   To move this into Patch/Generated/, make those member(s) `internal` (drop
//   `private`/`fileprivate`) and re-run `patchcli prepare`.
#if canImport(SwiftUI)
import SwiftUI
import PatchSDK
import PatchSwiftUI
import PatchRender
#if canImport(AVFoundation)
import AVFoundation
#endif
#if canImport(ActivityKit)
import ActivityKit
#endif
#if canImport(AdSupport)
import AdSupport
#endif
#if canImport(AppIntents)
import AppIntents
#endif
#if canImport(AppTrackingTransparency)
import AppTrackingTransparency
#endif
#if canImport(AudioToolbox)
import AudioToolbox
#endif
#if canImport(Combine)
import Combine
#endif
#if canImport(DeviceActivity)
import DeviceActivity
#endif
#if canImport(EventKit)
import EventKit
#endif
#if canImport(ExtensionKit)
import ExtensionKit
#endif
#if canImport(FamilyControls)
import FamilyControls
#endif
#if canImport(Foundation)
import Foundation
#endif
#if canImport(GoogleSignIn)
import GoogleSignIn
#endif
#if canImport(HealthKit)
import HealthKit
#endif
#if canImport(LocalAuthentication)
import LocalAuthentication
#endif
#if canImport(ManagedSettings)
import ManagedSettings
#endif
#if canImport(Observation)
import Observation
#endif
#if canImport(SafariServices)
import SafariServices
#endif
#if canImport(SwiftData)
import SwiftData
#endif
#if canImport(UIKit)
import UIKit
#endif
#if canImport(UserNotifications)
import UserNotifications
#endif
#if canImport(WidgetKit)
import WidgetKit
#endif

extension CustomBottomNavBar {
    /// Native renderers for this view's non-lowerable leaves, keyed by the
    /// shipped tree's opaque-slot id. Each is a FACTORY `([String]) -> AnyView`:
    /// a PARAMETERIZED leaf (a slotted custom view with lifted string-literal
    /// args) substitutes the runtime-supplied `a[k]` into its template, so an
    /// OTA patch that only edited a string ships through here (the id is
    /// structural/stable, the new value rides WASM in `BodyEmission.slotArgs`).
    /// A plain leaf ignores its args. Empty for a fully-lowered view.
    @MainActor func __patchSlots() -> [String: ([String]) -> AnyView] {
        var __s: [String: ([String]) -> AnyView] = [:]
        __s["op_2d2c12295ecc217b"] = { (_: [String]) in AnyView(HStack(spacing: 4) {
            ForEach(0..<tabs.count, id: \.self) { index in
                let tab = tabs[index]
                CartoonTabButton(
                    icon: tab.icon,
                    title: tab.title,
                    index: index,
                    selectedTab: $selectedTab,
                    activeColor: tab.color
                )
            }
        }
        .padding(.horizontal, 4)
        .padding(.vertical, 7)
        .background(Color.white)
        .clipShape(Capsule())
        .overlay(
            Capsule().stroke(Color.cartoonBorder, lineWidth: 2.2)
        )
        .shadow(color: .cartoonBorder, radius: 0, x: 3, y: 3)
        .padding(.horizontal, HIGSpacing.xs)) }
        return __s
    }

    /// Resolved design-system token values for this view's `.hostToken(id)`/
    /// `.fontToken(id)`/numeric/string token slots. Empty when the view uses none.
    @MainActor func __patchTokens() -> [String: PatchHostToken] {
        [:]
    }

    /// Per-row indexed native-action slots for this view's `.indexedForEachSlot`
    /// nodes. Each natively evaluates the body-local collection (over `self`) →
    /// a row count + a per-row factory `(Int) -> AnyView` (closing over `self`, so
    /// each row's real per-row native action works). Empty when the view has none.
    @MainActor func __patchRowSlots() -> [String: PatchRowSlot] {
        [:]
    }

    /// Native-action slots for this view's `.actionSlotButton` nodes — an actions-list
    /// Button (`.swipeActions`/`.toolbar`/`.alert`/`Menu`/`.contextMenu`) whose action is a
    /// native method call. Each closure (`() -> Void`, over `self`) runs the real action;
    /// the SDK wires it to the reconstituted Button by id. Empty when the view has none.
    @MainActor func __patchActionSlots() -> [String: () -> Void] {
        [:]
    }

    /// Native effect-modifier slots for this view's `.nativeEffectSlot` modifiers — an
    /// undispatchable `.task`/`.onAppear`/`.refreshable`/`.onSubmit`/gesture whose closure
    /// runs a native side-effect. Each closure (`(AnyView) -> AnyView`, over `self`) applies
    /// the real modifier to its content; the SDK applies it to the rendered subtree by id.
    /// Empty when the view has none.
    @MainActor func __patchEffectSlots() -> [String: (AnyView) -> AnyView] {
        [:]
    }

    /// Child-view callback slots for this view's `.callbackSlot` nodes — a custom child-view
    /// call whose `() -> Void` closure arg lowers to a WASM dispatch sequence. Each closure
    /// returns the full child-view `AnyView` with the callback arg replaced by a stable
    /// forwarder `{ self.__patchDispatchCallback("<id>") }`. The SDK fills the opaque slot
    /// position from this table by id. Empty when the view has no callback slots.
    @MainActor func __patchCallbackSlots() -> [String: () -> AnyView] {
        [:]
    }
}

#endif
// @generated — END OF AUTOGENERATED SECTION. DO NOT EDIT ABOVE (regenerated by `patchcli prepare`).
// PATCH-THUNKS-END
