//
//  SplashScreenView.swift
//  learning
//
//  Created by macbook on 8/30/26.
//

import SwiftUI

struct SplashScreenView: View {
    @Binding var isSplashActive: Bool
    
    // Animation States
    @State private var scale: CGFloat = 0.6
    @State private var opacity: Double = 0.0
    @State private var rotation: Double = -10.0
    @State private var textOffset: CGFloat = 20.0
    @State private var sparkleScale: CGFloat = 0.0

    dynamic var body: some View {
        ZStack {
            // Latar Belakang Kartun Retro Terang
            Color.cartoonBg
                .ignoresSafeArea()

            VStack(spacing: 20) {
                // 1. Logo Kartun Membal & Berputar Halus
                ZStack {
                    // Lingkaran Luar Bayangan Stiker
                    Circle()
                        .fill(Color.cartoonYellow)
                        .frame(width: 110, height: 110)
                        .overlay(
                            Circle().stroke(Color.cartoonBorder, lineWidth: CartoonMetrics.thickBorderWidth)
                        )
                        .shadow(color: .cartoonBorder, radius: 0, x: 4, y: 4)

                    // Ikon Vektor Checklist Kartun
                    Image(systemName: "checklist.checked")
                        .font(.system(size: 54, weight: .black))
                        .foregroundColor(.cartoonTextPrimary)

                    // Stiker Bintang / Sparkle di Pojok Kanan Atas
                    Image(systemName: "sparkle")
                        .font(.system(size: 24, weight: .bold))
                        .foregroundColor(.orange)
                        .offset(x: 48, y: -45)
                        .scaleEffect(sparkleScale)
                }
                .rotationEffect(.degrees(rotation))
                .scaleEffect(scale)
                .opacity(opacity)

                // 2. Judul Aplikasi Bergaya Kartun Pop
                VStack(spacing: 6) {
                    Text("Activity Tracker")
                        .font(.system(size: 26, weight: .heavy, design: .rounded))
                        .foregroundColor(.cartoonTextPrimary)

                    HStack(spacing: 4) {
                        Text("Plan • Focus • Accomplish")
                            .font(.system(size: 12, weight: .bold, design: .rounded))
                            .foregroundColor(.secondary)
                        Image(systemName: "bolt.fill")
                            .font(.system(size: 11, weight: .bold))
                            .foregroundColor(.cartoonOrange)
                    }
                }
                .offset(y: textOffset)
                .opacity(opacity)
            }
        }
        .preferredColorScheme(.light)
        .onAppear {
            // Animasi Masuk: Logo membal (Spring Animation)
            withAnimation(.spring(response: 0.65, dampingFraction: 0.6, blendDuration: 0)) {
                scale = 1.0
                opacity = 1.0
                rotation = 0.0
                textOffset = 0.0
            }

            // Animasi Sparkle muncul dengan delay
            withAnimation(.spring(response: 0.5, dampingFraction: 0.5).delay(0.3)) {
                sparkleScale = 1.2
            }

            // Durasi Splash Screen (1.8 detik), lalu transisi keluar ke layar utama
            DispatchQueue.main.asyncAfter(deadline: .now() + 1.8) {
                withAnimation(.spring(response: 0.4, dampingFraction: 0.8)) {
                    isSplashActive = false
                }
            }
        }
    }
}

#Preview {
    SplashScreenView(isSplashActive: .constant(true))
}

// PATCH-THUNKS-BEGIN (generated by `patchcli prepare` — DO NOT EDIT)
// @generated
// =========================================================================
// AUTOGENERATED BY `patchcli prepare` — DO NOT EDIT THIS SECTION.
//
// Do NOT edit any code in this generated section — neither by hand NOR with
// an AI coding assistant (Copilot, Cursor, Claude, etc.).
//
// Reason: this block is REGENERATED on every `patchcli prepare` run (which
// also runs automatically inside `patchcli build`/`push`/`release`). Any
// manual change here is SILENTLY OVERWRITTEN on the next prepare, and an
// inconsistent thunk can break the OTA fingerprint (causing a MISMATCH that
// blocks your release).
//
// To change a view's behaviour: edit the VIEW SOURCE FILE itself — never
// this generated thunk. To remove this section entirely, delete the block
// from BEGIN to END and re-run `patchcli prepare` (it recreates it).
// =========================================================================
// Patch kept the patch-thunk code for the view(s) below in YOUR file because each is
// declared `private`/`fileprivate` (or its body host-resolves a `private` member) —
// and Swift access control is file-scoped, so a thunk in the separate
// `Patch/Generated/` folder cannot reach it. Only the minimum that genuinely needs
// file-scoped access is here.
// SplashScreenView: helper methods kept here — its body reads private member(s): rotation, scale, sparkleScale, textOffset.
//   To move this into Patch/Generated/, make those member(s) `internal` (drop
//   `private`/`fileprivate`) and re-run `patchcli prepare`.
#if canImport(SwiftUI)
import SwiftUI
import PatchSDK
import PatchSwiftUI
import PatchRender
#if canImport(AVFoundation)
import AVFoundation
#endif
#if canImport(ActivityKit)
import ActivityKit
#endif
#if canImport(AdSupport)
import AdSupport
#endif
#if canImport(AppIntents)
import AppIntents
#endif
#if canImport(AppTrackingTransparency)
import AppTrackingTransparency
#endif
#if canImport(AudioToolbox)
import AudioToolbox
#endif
#if canImport(Combine)
import Combine
#endif
#if canImport(DeviceActivity)
import DeviceActivity
#endif
#if canImport(EventKit)
import EventKit
#endif
#if canImport(ExtensionKit)
import ExtensionKit
#endif
#if canImport(FamilyControls)
import FamilyControls
#endif
#if canImport(Foundation)
import Foundation
#endif
#if canImport(GoogleSignIn)
import GoogleSignIn
#endif
#if canImport(HealthKit)
import HealthKit
#endif
#if canImport(LocalAuthentication)
import LocalAuthentication
#endif
#if canImport(ManagedSettings)
import ManagedSettings
#endif
#if canImport(Observation)
import Observation
#endif
#if canImport(SafariServices)
import SafariServices
#endif
#if canImport(SwiftData)
import SwiftData
#endif
#if canImport(UIKit)
import UIKit
#endif
#if canImport(UserNotifications)
import UserNotifications
#endif
#if canImport(WidgetKit)
import WidgetKit
#endif

extension SplashScreenView {
    /// Native renderers for this view's non-lowerable leaves, keyed by the
    /// shipped tree's opaque-slot id. Each is a FACTORY `([String]) -> AnyView`:
    /// a PARAMETERIZED leaf (a slotted custom view with lifted string-literal
    /// args) substitutes the runtime-supplied `a[k]` into its template, so an
    /// OTA patch that only edited a string ships through here (the id is
    /// structural/stable, the new value rides WASM in `BodyEmission.slotArgs`).
    /// A plain leaf ignores its args. Empty for a fully-lowered view.
    @MainActor func __patchSlots() -> [String: ([String]) -> AnyView] {
        var __s: [String: ([String]) -> AnyView] = [:]
        __s["op_97b0831f1c79aa8a"] = { (a: [String]) in a.count >= 2 ? AnyView(ZStack {
                    // Lingkaran Luar Bayangan Stiker
                    Circle()
                        .fill(Color.cartoonYellow)
                        .frame(width: 110, height: 110)
                        .overlay(
                            Circle().stroke(Color.cartoonBorder, lineWidth: CartoonMetrics.thickBorderWidth)
                        )
                        .shadow(color: .cartoonBorder, radius: 0, x: 4, y: 4)

                    // Ikon Vektor Checklist Kartun
                    Image(systemName: a[0])
                        .font(.system(size: 54, weight: .black))
                        .foregroundColor(.cartoonTextPrimary)

                    // Stiker Bintang / Sparkle di Pojok Kanan Atas
                    Image(systemName: a[1])
                        .font(.system(size: 24, weight: .bold))
                        .foregroundColor(.orange)
                        .offset(x: 48, y: -45)
                        .scaleEffect(sparkleScale)
                }
                .rotationEffect(.degrees(rotation))
                .scaleEffect(scale)) : AnyView(EmptyView()) }
        __s["op_bda598028d73d74e"] = { (a: [String]) in a.count >= 3 ? AnyView(VStack(spacing: 6) {
                    Text(LocalizedStringKey(a[0]))
                        .font(.system(size: 26, weight: .heavy, design: .rounded))
                        .foregroundColor(.cartoonTextPrimary)

                    HStack(spacing: 4) {
                        Text(LocalizedStringKey(a[1]))
                            .font(.system(size: 12, weight: .bold, design: .rounded))
                            .foregroundColor(.secondary)
                        Image(systemName: a[2])
                            .font(.system(size: 11, weight: .bold))
                            .foregroundColor(.cartoonOrange)
                    }
                }
                .offset(y: textOffset)) : AnyView(EmptyView()) }
        return __s
    }

    /// Resolved design-system token values for this view's `.hostToken(id)`/
    /// `.fontToken(id)`/numeric/string token slots. Empty when the view uses none.
    @MainActor func __patchTokens() -> [String: PatchHostToken] {
        var __t: [String: PatchHostToken] = [:]
        __t["ct_896c50b68f3107a3"] = .color(Color.cartoonBg)
        return __t
    }

    /// Per-row indexed native-action slots for this view's `.indexedForEachSlot`
    /// nodes. Each natively evaluates the body-local collection (over `self`) →
    /// a row count + a per-row factory `(Int) -> AnyView` (closing over `self`, so
    /// each row's real per-row native action works). Empty when the view has none.
    @MainActor func __patchRowSlots() -> [String: PatchRowSlot] {
        [:]
    }

    /// Native-action slots for this view's `.actionSlotButton` nodes — an actions-list
    /// Button (`.swipeActions`/`.toolbar`/`.alert`/`Menu`/`.contextMenu`) whose action is a
    /// native method call. Each closure (`() -> Void`, over `self`) runs the real action;
    /// the SDK wires it to the reconstituted Button by id. Empty when the view has none.
    @MainActor func __patchActionSlots() -> [String: () -> Void] {
        [:]
    }

    /// Native effect-modifier slots for this view's `.nativeEffectSlot` modifiers — an
    /// undispatchable `.task`/`.onAppear`/`.refreshable`/`.onSubmit`/gesture whose closure
    /// runs a native side-effect. Each closure (`(AnyView) -> AnyView`, over `self`) applies
    /// the real modifier to its content; the SDK applies it to the rendered subtree by id.
    /// Empty when the view has none.
    @MainActor func __patchEffectSlots() -> [String: (AnyView) -> AnyView] {
        [:]
    }

    /// Child-view callback slots for this view's `.callbackSlot` nodes — a custom child-view
    /// call whose `() -> Void` closure arg lowers to a WASM dispatch sequence. Each closure
    /// returns the full child-view `AnyView` with the callback arg replaced by a stable
    /// forwarder `{ self.__patchDispatchCallback("<id>") }`. The SDK fills the opaque slot
    /// position from this table by id. Empty when the view has no callback slots.
    @MainActor func __patchCallbackSlots() -> [String: () -> AnyView] {
        [:]
    }
}

#endif
// @generated — END OF AUTOGENERATED SECTION. DO NOT EDIT ABOVE (regenerated by `patchcli prepare`).
// PATCH-THUNKS-END
